### ISSUE TITLE
I can't do the installation

### ISSUE THREAD

**Issue by zizhuxuaner** [itexia/yii2-bootstrap-table#6]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - itexia/yii2-bootstrap-table 0.0.4 requires bower-asset/bootstrap-table-fixed-columns dev-master -> satisfiable by bower-asset/bootstrap-table-fixed-columns[dev-master] but these conflict with your requirements or minimum-stability.
    - itexia/yii2-bootstrap-table 0.0.3 requires bower-asset/bootstrap-table-fixed-columns dev-master -> satisfiable by bower-asset/bootstrap-table-fixed-columns[dev-master] but these conflict with your requirements or minimum-stability.
    - itexia/yii2-bootstrap-table 0.0.2 requires bower-asset/bootstrap-table-fixed-columns dev-master -> satisfiable by bower-asset/bootstrap-table-fixed-columns[dev-master] but these conflict with your requirements or minimum-stability.
    - itexia/yii2-bootstrap-table 0.0.1 requires bower-asset/bootstrap-table-fixed-columns dev-master -> satisfiable by bower-asset/bootstrap-table-fixed-columns[dev-master] but these conflict with your requirements or minimum-stability.
    - Installation request for itexia/yii2-bootstrap-table * -> satisfiable by itexia/yii2-bootstrap-table[0.0.1, 0.0.2, 0.0.3, 0.0.4].

**Comment by freshp** [comment]
Sorry for the late response, yesterday we updated the package and these changes should also solve the given problem.
Otherwise please reopen it.
